[uwsgi]
stats = /tmp/stats.socket
http = 0.0.0.0:5000
module = reana_workflow_controller.app:app
master = true
processes = 2
threads = 2
enable-threads = true
single-interpreter = true
need-app = true
vacuum = true
wsgi-disable-file-wrapper = true

buffer-size = 8192

die-on-term = true
hook-master-start = unix_signal:2 gracefully_kill_them_all
hook-master-start = unix_signal:15 gracefully_kill_them_all

max-fd = 1048576
